spring:
  profiles:
    active: dev
  jackson:
    date-format:  yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-delete-field: deleted
      logic-not-delete-value: 0
